#define ONESHOT_TAP_TOGGLE 3

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 4000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "qZJ7A/dr6RG"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

